server:
  port: 9004

spring:
  application:
    name: recruiting-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/tensquare_article?useSSL=false
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.1.102

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true #跨域访问
