server:
  port: 12000

spring:
  application:
    name: recruiting-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/imsadan/propertise.git
  rabbitmq:
    host: 101.200.58.52
    password: qq520821

management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus‐refresh
