server: 
  port: 9005
spring: 
  application:  
    name: recruiting-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/tensquare_gathering?useSSL=false
    username: root
    password: 1234
  jpa: 
    database: MySQL
    show-sql: true
